"""empty message

Revision ID: 4705d01d4a2f
Revises: 0c006c3d90c4
Create Date: 2025-08-02 00:16:05.449372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4705d01d4a2f'
down_revision = '0c006c3d90c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renter_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('user_name', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('budget', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('criminal_record', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('parking', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.Integer(), nullable=False))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.DATE(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.String(length=20),
               type_=sa.DATE(),
               existing_nullable=True)

    with op.batch_alter_table('renter_form', schema=None) as batch_op:
        batch_op.drop_column('phone_number')
        batch_op.drop_column('parking')
        batch_op.drop_column('criminal_record')
        batch_op.drop_column('bedrooms')
        batch_op.drop_column('budget')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('user_name')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
