"""empty message

Revision ID: a53881338fa3
Revises: f9176fa01388
Create Date: 2025-08-08 22:48:56.920385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53881338fa3'
down_revision = 'f9176fa01388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('security_question', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('security_answer', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('security_answer')
        batch_op.drop_column('security_question')

    # ### end Alembic commands ###
