"""empty message

Revision ID: b788c9909f21
Revises: 1180e4eb6afd
Create Date: 2025-08-02 05:41:53.247262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b788c9909f21'
down_revision = '1180e4eb6afd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Date(),
               existing_nullable=True,
               postgresql_using="dob::date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('dob',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
