"""empty message

Revision ID: e29d53f82ebb
Revises: f767c5a0bbe4
Create Date: 2025-08-12 01:36:03.546762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29d53f82ebb'
down_revision = 'f767c5a0bbe4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renter_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employment', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('renter_form', schema=None) as batch_op:
        batch_op.drop_column('employment')

    # ### end Alembic commands ###
